org.gradle.caching=true
org.gradle.configuration-cache=true

# The default 384m metaspace is too small for a build that also runs KSP.
org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g
kotlin.daemon.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=1g

# May be overridden by the user
pokemmo.executable=C:/Program Files/PokeMMO/PokeMMO.exe
pokemmo.workingDir=C:/Program Files/PokeMMO