create extension if not exists pgcrypto;

create table "character" (
    id              bigserial   not null,
    user_id         int         not null,
    name            varchar(16) not null unique,
    name_prefix     varchar(16) not null default '',
    rival_sex       smallint    not null default 0,
    created_at      timestamp   not null default current_timestamp,
    last_login      timestamp   not null default current_timestamp,
    money           int         not null default 3000,
    permissions     int         not null default 0,
    remaining_safari_steps  smallint not null default 0,
    remaining_safari_balls  smallint not null default 0,
    pc_extra_slots  smallint    not null default 0,
    battle_box_extra_slots   smallint not null default 0,
    template_amount smallint   not null default 0,
    position_region_id  smallint not null default 0,
    position_bank_id    smallint not null default 1,
    position_map_id     smallint not null default 1,
    position_x      smallint    not null default 100,
    position_y      smallint    not null default 100,
    repel_left      smallint    not null default 0,
    repel_item_id   smallint    not null default 0,
    lure_left       smallint    not null default 0,
    lure_item_id    smallint    not null default 0,
    primary key (id)
);

create table pokemon (
    id              bigserial   not null,
    character_id    bigint      not null,
    container       smallint    not null default 0,
    container_slot  smallint    not null default 0,
    dex_id          int         not null,
    seed            int         not null,
    ot              varchar(16) not null,
    nickname        varchar(32) not null,
    level           smallint    not null default 1,
    hp              smallint    not null default 10,
    xp              int         not null default 0,
    ivs             int         not null default 0,
    ev_hp           smallint    not null default 0,
    ev_atk          smallint    not null default 0,
    ev_def          smallint    not null default 0,
    ev_spatk        smallint    not null default 0,
    ev_spdef        smallint    not null default 0,
    ev_spd          smallint    not null default 0,
    move1_id        smallint    not null default 0,
    move1_pp        smallint    not null default 0,
    move2_id        smallint    not null default 0,
    move2_pp        smallint    not null default 0,
    move3_id        smallint    not null default 0,
    move3_pp        smallint    not null default 0,
    move4_id        smallint    not null default 0,
    move4_pp        smallint    not null default 0,
    is_shiny        boolean     not null default false,
    has_hidden_ability  boolean not null default false,
    is_alpha        boolean     not null default false,
    is_secret       boolean     not null default false,
    is_fateful_encounter boolean not null default false,
    is_raid_encounter   boolean not null default false,
    caught_at       timestamp   not null default current_timestamp,
    primary key (id),
    foreign key (character_id) references "character"(id) on delete cascade
);

create table item (
    id              bigserial   not null,
    character_id    bigint      not null,
    item_id         int         not null,
    amount          int         not null default 1,
    primary key (id),
    foreign key (character_id) references "character"(id) on delete cascade
);
