create extension if not exists pgcrypto;

create table "character" (
    id bigserial primary key,
    user_id int not null,
    name varchar(16) not null unique,
    name_prefix varchar(16) not null default '',
    rival_sex smallint not null default 0,
    created_at timestamp not null default now(),
    last_login timestamp not null default now(),
    money int not null default 3000,
    permissions int not null default 0,
    remaining_safari_steps smallint not null default 0,
    remaining_safari_balls smallint not null default 0,
    pc_extra_slots smallint not null default 0,
    battle_box_extra_slots smallint not null default 0,
    template_amount smallint not null default 0,
    position_region_id smallint not null default 1,
    position_bank_id smallint not null default 51,
    position_map_id smallint not null default 3,
    position_x smallint not null default 4,
    position_y smallint not null default 2,
    repel_left smallint not null default 0,
    repel_item_id smallint not null default 0,
    lure_left smallint not null default 0,
    lure_item_id smallint not null default 0
);

create table pokemon (
    id bigserial primary key,
    character_id bigint not null references "character"(id) on delete cascade,
    dex_id int not null,
    level int not null,
    exp int not null default 0,
    hp_ev smallint not null default 0,
    attack_ev smallint not null default 0,
    defense_ev smallint not null default 0,
    sp_attack_ev smallint not null default 0,
    sp_defense_ev smallint not null default 0,
    speed_ev smallint not null default 0,
    hp_iv smallint not null default 0,
    attack_iv smallint not null default 0,
    defense_iv smallint not null default 0,
    sp_attack_iv smallint not null default 0,
    sp_defense_iv smallint not null default 0,
    speed_iv smallint not null default 0,
    move1_id int not null default 0,
    move2_id int not null default 0,
    move3_id int not null default 0,
    move4_id int not null default 0,
    hp_stat int not null default 0,
    attack_stat int not null default 0,
    defense_stat int not null default 0,
    sp_attack_stat int not null default 0,
    sp_defense_stat int not null default 0,
    speed_stat int not null default 0,
    held_item_id int not null default 0,
    status_condition smallint not null default 0,
    levelMet int not null default 0,
    pokerus smallint not null default 0,
    gender smallint not null default 0,
    is_egg bool not null default false,
    is_shiny bool not null default false,
    nickname varchar(10) not null default '',
    ot_id int not null default 0,
    ot_name varchar(16) not null default '',
    markings int not null default 0,
    friendship smallint not null default 70,
    ability_id smallint not null default 0,
    nature smallint not null default 0,
    slot smallint not null default 0
);

create table item (
    id bigserial primary key,
    character_id bigint not null references "character"(id) on delete cascade,
    item_id int not null,
    amount int not null default 1,
    slot smallint not null default 0
);
