@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package de.fiereu.openmmo.server.login.jooq.tables.references


import de.fiereu.openmmo.server.login.jooq.tables.User



/**
 * The table <code>public.user</code>.
 */
val USER: User = User.USER
