/*
 * This file is generated by jOOQ.
 */
package de.fiereu.openmmo.server.login.jooq.tables.records


import de.fiereu.openmmo.server.login.jooq.tables.User

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UserRecord() : UpdatableRecordImpl<UserRecord>(User.USER) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(1, value)
        get(): LocalDateTime? = get(1) as LocalDateTime?

    open var username: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var password: ByteArray?
        set(value): Unit = set(3, value)
        get(): ByteArray? = get(3) as ByteArray?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised UserRecord
     */
    constructor(id: Int? = null, createdAt: LocalDateTime? = null, username: String? = null, password: ByteArray? = null): this() {
        this.id = id
        this.createdAt = createdAt
        this.username = username
        this.password = password
        resetTouchedOnNotNull()
    }
}
