@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package de.fiereu.openmmo.server.login.jooq.keys


import de.fiereu.openmmo.server.login.jooq.tables.User
import de.fiereu.openmmo.server.login.jooq.tables.records.UserRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val USER_PKEY: UniqueKey<UserRecord> = Internal.createUniqueKey(User.USER, DSL.name("user_pkey"), arrayOf(User.USER.ID), true)
val USER_USERNAME_KEY: UniqueKey<UserRecord> = Internal.createUniqueKey(User.USER, DSL.name("user_username_key"), arrayOf(User.USER.USERNAME), true)
